# Generated by Django 3.1.5 on 2021-02-07 03:47

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='year')),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('ABS', 'ABS'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Heated seats', 'Heated seats'), ('Central locking', 'Central locking'), ('Parking sensors', 'Parking sensors'), ('Power Steering', 'Power Steering'), ('Rear View Camera', 'Rear View Camera'), ('Electric windows', 'Electric windows'), ('Start/Stop', 'Start/Stop'), ('Traction control', 'Traction control'), ('ESP', 'ESP'), ('4-wheel drive', '4-wheel drive'), ('Alarm', 'Alarm'), ('Climate control', 'Climate control')], max_length=205)),
                ('body_style', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('Van', 'Van'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe')], max_length=100)),
                ('engine_power', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Diesel')], max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('doors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('passengers', models.IntegerField()),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
