# Generated by Django 3.1.5 on 2021-02-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210207_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
    ]
