# Generated by Django 3.1.5 on 2021-02-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_milage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine_power',
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
