# Generated by Django 3.1.5 on 2021-02-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210207_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('Accidented', 'Accidented')], max_length=100),
        ),
    ]
