# Generated by Django 3.1.5 on 2021-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210208_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Saloon', 'Saloon'), ('Estate', 'Estate'), ('Van', 'Van'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Truck', 'Truck')], max_length=100),
        ),
    ]
