# Generated by Django 3.1.5 on 2021-02-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210208_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drivetrain_choices',
            field=models.CharField(blank=True, choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD')], max_length=10),
        ),
    ]
